app = "deepgram-flux-streaming-demo"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
auto_rollback = true

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[services]]
protocol = "tcp"
internal_port = 3000
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]

[[vm]]
size = "shared-cpu-1x"
memory = 1024
